apiVersion: v1
kind: Pod
metadata:
  name: benchmark
  namespace: default
spec:
  nodeSelector:
    beta.kubernetes.io/instance-type: p3.2xlarge
  tolerations:
    - key: "nvidia.com/gpu"
      operator: "Equal"
      value: "present"
      effect: "NoSchedule"
  containers:
  - name: benchmark
    image: 252773325474.dkr.ecr.us-east-1.amazonaws.com/fcam/backend
    command: 
      - sleep
      - infinity
    resources:
      limits:
        nvidia.com/gpu: 1
  restartPolicy: Never
